version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  currency_updater:
    build: .
    command: python currency_updater.py
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  bot:
    build: .
    command: python bot.py
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONUNBUFFERED=1
